from typing import Any

QT_API: str

ALIGN_LEFT: Any
EVENT_KEY_PRESS: Any
HORIZONTAL: Any
KEY_DOWN: Any
KEY_UP: Any
NO_EDIT_TRIGGERS: Any
PASSWORD_ECHO: Any
SELECT_ROWS: Any
SINGLE_SELECTION: Any
Signal: Any
Qt: Any
QEvent: Any
USER_ROLE: Any
VERTICAL: Any
WEB_ATTR_FILE_URLS: Any

class QApplication:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def exec(self) -> int: ...
    def exec_(self) -> int: ...
    @staticmethod
    def instance() -> Any: ...

class QBrush: ...
class QCheckBox: ...
class QColor: ...
class QComboBox: ...
class QDoubleSpinBox: ...
class QFormLayout: ...
class QGraphicsOpacityEffect: ...
class QGridLayout: ...
class QGroupBox: ...
class QHBoxLayout: ...
class QHeaderView: ...
class QLabel: ...
class QLineEdit: ...
class QMainWindow: ...
class QMessageBox: ...
class QPlainTextEdit: ...
class QProgressBar: ...
class QPropertyAnimation: ...
class QPushButton: ...
class QRadioButton: ...
class QScrollArea: ...
class QSpinBox: ...
class QSplitter: ...
class QTableWidget: ...
class QTableWidgetItem: ...
class QTabWidget: ...
class QThread: ...
class QTimer: ...
class QUrl: ...
class QWebEngineView: ...
class QVBoxLayout: ...
class QWidget: ...

def app_exec(app: QApplication) -> int: ...
